version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      # Group Playwright dependencies together
      playwright:
        patterns:
          - "@playwright/test"
          - "playwright"
