name: E2E tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  test:
    name: Node.js {{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - 20
          - 22
          - 24
    timeout-minutes: 30
    defaults:
      run:
        working-directory: playground
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: |
          pnpm install --frozen-lockfile
          pnpm exec playwright install --with-deps chromium --no-shell
      - run: pnpm build
        working-directory: packages/astro-umami
      - run: pnpm test
