name: E2E tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 22.18.0
          - 24
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter="./playground/*" exec playwright install --with-deps chromium --no-shell
      - run: pnpm build
      - run: pnpm test
